PublicBodyCategories.add(:it, [
        "Miscellaneous",
            [ "parchi_nazionali_consorzi_e_enti_gestori_di_parchi_e_aree_naturali_protette", "Parchi Nazionali, Consorzi e Enti Gestori di Parchi e Aree Naturali Protette", "parchi nazionali, consorzi e enti gestori di parchi e aree naturali protette" ],
            [ "autorita_di_bacino", "Autorità di Bacino", "autorità di bacino" ],
            [ "consorzi_di_bacino_imbrifero_montano", "Consorzi di Bacino Imbrifero Montano", "consorzi di bacino imbrifero montano" ],
            [ "forze_di_polizia_ad_ordinamento_civile_e_militare_per_la_tutela_dellordine_e_della_sicurezza_pubblica", "Forze di Polizia ad Ordinamento Civile e Militare per la Tutela dell'Ordine e della Sicurezza Pubblica", "forze di polizia ad ordinamento civile e militare per la tutela dell'ordine e della sicurezza pubblica" ],
            [ "istituti_zooprofilattici_sperimentali", "Istituti Zooprofilattici Sperimentali", "istituti zooprofilattici sperimentali" ],
            [ "agenzie_enti_e_consorzi_pubblici_per_il_diritto_allo_studio_universitario", "Agenzie, Enti e Consorzi Pubblici per il Diritto allo Studio Universitario", "agenzie, enti e consorzi pubblici per il diritto allo studio universitario" ],
            [ "agenzie_regionali_e_provinciale_per_la_rappresentanza_negoziale", "Agenzie Regionali e Provinciale per la Rappresentanza Negoziale", "agenzie regionali e provinciale per la rappresentanza negoziale" ],
            [ "autorita_portuali", "Autorità Portuali", "autorità portuali" ],
            [ "organi_costituzionali_e_di_rilievo_costituzionale", "Organi Costituzionali e di Rilievo Costituzionale", "organi costituzionali e di rilievo costituzionale" ],
            [ "unioni_di_comuni_e_loro_consorzi_e_associazioni", "Unioni di Comuni e loro Consorzi e Associazioni", "unioni di comuni e loro consorzi e associazioni" ],
            [ "enti_pubblici_nazionali_non_economici", "Enti Pubblici Nazionali Non Economici", "enti pubblici nazionali non economici" ],
            [ "automobil_club_federati_aci", "Automobil Club Federati ACI", "automobil club federati aci" ],
            [ "province_e_loro_consorzi_e_associazioni", "Province e Loro Consorzi e Associazioni", "province e loro consorzi e associazioni" ],
            [ "agenzie_ed_enti_regionali_di_sviluppo_agricolo", "Agenzie ed Enti Regionali di Sviluppo Agricolo", "agenzie ed enti regionali di sviluppo agricolo" ],
            [ "aziende_sanitarie_locali", "Aziende Sanitarie Locali", "aziende sanitarie locali" ],
            [ "enti_pubblici_produttori_di_servizi_assistenziali_ricreativi_e_culturali", "Enti Pubblici Produttori di Servizi Assistenziali, Ricreativi e Culturali", "enti pubblici produttori di servizi assistenziali, ricreativi e culturali" ],
            [ "consorzi_interuniversitari_di_ricerca", "Consorzi Interuniversitari di Ricerca", "consorzi interuniversitari di ricerca" ],
            [ "altri_enti_locali", "Altri Enti Locali", "altri enti locali" ],
            [ "camere_di_commercio_industria_artigianato_e_agricoltura_e_unioni_regionali", "Camere di Commercio, Industria, Artigianato e Agricoltura e Unioni Regionali", "camere di commercio, industria, artigianato e agricoltura e unioni regionali" ],
            [ "comunita_montane_e_loro_consorzi_e_associazioni", "Comunità Montane e loro Consorzi e Associazioni", "comunità montane e loro consorzi e associazioni" ],
            [ "agenzie_ed_enti_regionali_per_la_ricerca_e_per_lambiente", "Agenzie ed Enti Regionali per la Ricerca e per l'Ambiente", "agenzie ed enti regionali per la ricerca e per l'ambiente" ],
            [ "agenzie_regionali_sanitarie", "Agenzie Regionali Sanitarie", "agenzie regionali sanitarie" ],
            [ "presidenza_del_consiglio_dei_ministri_e_ministeri_e_avvocature_dello_stato", "Presidenza del Consiglio dei Ministri e Ministeri e Avvocature dello Stato", "presidenza del consiglio dei ministri e ministeri e avvocature dello stato" ],
            [ "agenzie_ed_enti_per_il_turismo", "Agenzie ed Enti per il Turismo", "agenzie ed enti per il turismo" ],
            [ "universita_e_istituti_di_istruzione_universitaria_pubblici", "Università e Istituti di Istruzione Universitaria Pubblici", "università e istituti di istruzione universitaria pubblici" ],
            [ "enti_e_istituzioni_di_ricerca_pubblici", "Enti e Istituzioni di Ricerca Pubblici", "enti e istituzioni di ricerca pubblici" ],
            [ "autorita_di_ambito_territoriale_ottimale", "Autorità di Ambito Territoriale Ottimale", "autorità di ambito territoriale ottimale" ],
            [ "consorzi_tra_amministrazioni_locali", "Consorzi tra Amministrazioni Locali", "consorzi tra amministrazioni locali" ],
            [ "comuni_e_loro_consorzi_e_associazioni", "Comuni e loro Consorzi e Associazioni", "comuni e loro consorzi e associazioni" ],
            [ "autorita_amministrative_indipendenti", "Autorità Amministrative Indipendenti", "autorità amministrative indipendenti" ],
            [ "consorzi_per_larea_di_sviluppo_industriale", "Consorzi per l'Area di Sviluppo Industriale", "consorzi per l'area di sviluppo industriale" ],
            [ "aziende_pubbliche_di_servizi_alla_persona", "Aziende Pubbliche di Servizi alla Persona", "aziende pubbliche di servizi alla persona" ],
            [ "fondazioni_lirico_sinfoniche", "Fondazioni Lirico, Sinfoniche", "fondazioni lirico, sinfoniche" ],
            [ "consorzi_di_bonifica_e_loro_associazioni", "Consorzi di Bonifica e loro Associazioni", "consorzi di bonifica e loro associazioni" ],
            [ "enti_nazionali_di_previdenza_ed_assistenza_sociale_in_conto_economico_consolidato", "Enti Nazionali di Previdenza ed Assistenza Sociale in Conto Economico Consolidato", "enti nazionali di previdenza ed assistenza sociale in conto economico consolidato" ],
            [ "agenzie_regionali_per_le_erogazioni_in_agricoltura", "Agenzie Regionali per le Erogazioni in Agricoltura", "agenzie regionali per le erogazioni in agricoltura" ],
            [ "aziende_ospedaliere_aziende_ospedaliere_universitarie_policlinici_e_istituti_di_ricovero_e_cura_a_carattere_scientifico_pubblici", "Aziende Ospedaliere, Aziende Ospedaliere Universitarie, Policlinici e Istituti di Ricovero e Cura a Carattere Scientifico Pubblici", "aziende ospedaliere, aziende ospedaliere universitarie, policlinici e istituti di ricovero e cura a carattere scientifico pubblici" ],
            [ "teatri_stabili_ad_iniziativa_pubblica", "Teatri Stabili ad Iniziativa Pubblica", "teatri stabili ad iniziativa pubblica" ],
            [ "regioni_province_autonome_e_loro_consorzi_e_associazioni", "Regioni, Province Autonome e Loro Consorzi e Associazioni", "regioni, province autonome e loro consorzi e associazioni" ],
            [ "gestore_di_pubblici_servizi", "Gestore di Pubblici Servizi", "gestore di pubblici servizi" ],
            [ "aziende_e_consorzi_pubblici_territoriali_per_ledilizia_residenziale", "Aziende e Consorzi Pubblici Territoriali per l'Edilizia Residenziale", "aziende e consorzi pubblici territoriali per l'edilizia residenziale" ],
            [ "istituti_di_istruzione_statale_di_ogni_ordine_e_grado", "Istituti di Istruzione Statale di Ogni Ordine e Grado", "istituti di istruzione statale di ogni ordine e grado" ],
            [ "federazioni_nazionali_ordini_collegi_e_consigli_professionali", "Federazioni Nazionali, Ordini, Collegi e Consigli Professionali", "federazioni nazionali, ordini, collegi e consigli professionali" ],
            [ "agenzie_fiscali", "Agenzie Fiscali", "agenzie fiscali" ],
            [ "agenzie_ed_enti_regionali_del_lavoro", "Agenzie ed Enti Regionali del Lavoro", "agenzie ed enti regionali del lavoro" ],
    ]
)